backend:
  name: git-gateway
  branch: main 

media_folder: "static/images/uploads"
public_folder: "/images/uploads" 

collections:
  - name: "about"
    label: "Giới Thiệu"
    folder: "content/about"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Nội dung", name: "body", widget: "markdown" }

  - name: "attractions"
    label: "Địa Điểm Tham Quan"
    folder: "content/attractions"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tên địa điểm", name: "title", widget: "string" }
      - { label: "Hình ảnh", name: "image", widget: "image" }
      - { label: "Mô tả", name: "description", widget: "text" }

  - name: "gallery"
    label: "Thư Viện Ảnh"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tiêu đề ảnh", name: "title", widget: "string" }
      - { label: "Hình ảnh", name: "image", widget: "image" }

  - name: "contact"
    label: "Liên Hệ"
    folder: "content/contact"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Địa chỉ", name: "address", widget: "text" }
